/**
 * @author 		Amanda Bodnovits, RadialSpark
 * @date 		2/8/18
 * @description Services for Account
 */
public class AccountServices {
	// Constants
	public static String LOCATION_RECORD_TYPE = 'Location';
    public static String CARRIER_RECORD_TYPE = 'Carrier';
    //As a part of account restructuring requirement
    //public static Id LOCATION_RECORD_TYPE_ID = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = :LOCATION_RECORD_TYPE].Id;
    //public static Id CARRIER_RECORD_TYPE_ID = [SELECT Id FROM RecordType WHERE SObjectType = 'Account' AND DeveloperName = :CARRIER_RECORD_TYPE].Id;
}